// PixelIcons.ts - 像素图标系统，32x32基础分辨率，离屏Canvas缓存

const BASE_SIZE = 32;

// 每个图标用32x32的字符串数组，'.'=透明，其他字符=颜色键
// 简化的图标定义 - 用紧凑格式：每行一个字符串，32字符宽
type IconData = string[];

const ICON_DEFS: Record<string, { pixels: IconData; palette: Record<string, string> }> = {
  sword: {
    palette: { a: '#c0c0c0', b: '#808080', h: '#8B4513', p: '#FFD700' },
    pixels: [
      '..............................a.',
      '.........................a...a..',
      '........................a...a..',
      '.......................a...a...',
      '......................a...a....',
      '.....................a...a.....',
      '....................a...a......',
      '...................a...a.......',
      '..................a...a........',
      '.................a...a.........',
      '................a...a..........',
      '...............a...a...........',
      '..............a...a............',
      '.............a...a.............',
      '............a...a..............',
      '...........a...a...............',
      '..........a...a................',
      '.........a...a.................',
      '........a...a..................',
      '.......a...a...................',
      '......a...a....................',
      '.....a...a.....................',
      '....a...a......................',
      '...a...a.......................',
      '..a...a........................',
      '.a...a.........................',
      'a...a..........................',
      '....a..........................',
      '...hh..........................',
      '..hhhh.........................',
      '.hhhhhh........................',
      'hhhhhhh.......................',
    ],
  },
  shield: {
    palette: { a: '#4169E1', b: '#2a4494', c: '#FFD700', d: '#c0c0c0' },
    pixels: [
      '..............cccc..............',
      '.............cccccc.............',
      '............cccccccc............',
      '...........cccccccccc...........',
      '..........cccccccccccc..........',
      '.........cccccccccccccc.........',
      '........cccccccccccccccc........',
      '.......cccccccccccccccccc.......',
      '......cccccccccccccccccccc......',
      '.....cccccccccccccccccccccc.....',
      '....cccccccccccccccccccccccc....',
      '...cccccccccccccccccccccccccc...',
      '..cccccccccccccccccccccccccccc..',
      '.cccccccccccccccccccccccccccccc.',
      'cccccccccccccccccccccccccccccccc',
      'cccccccccccccccccccccccccccccccc',
      'cccccccccccccccccccccccccccccccc',
      '.cccccccccccccccccccccccccccccc.',
      '..cccccccccccccccccccccccccccc..',
      '...cccccccccccccccccccccccccc...',
      '....cccccccccccccccccccccccc....',
      '.....cccccccccccccccccccccc.....',
      '......cccccccccccccccccccc......',
      '.......cccccccccccccccccc.......',
      '........cccccccccccccccc........',
      '.........cccccccccccccc.........',
      '..........cccccccccccc..........',
      '...........cccccccccc...........',
      '............cccccccc............',
      '.............cccccc.............',
      '..............cccc..............',
      '................................',
    ],
  },
  bow: {
    palette: { a: '#8B4513', b: '#A0522D', s: '#c0c0c0' },
    pixels: [
      '................................',
      '.......a.......................',
      '......a.......................',
      '.....a.......................',
      '....a.......................',
      '...a.......................',
      '..a.......................',
      '.a.......................',
      'a.......................',
      'a.......................',
      'a.......................',
      'a.......................',
      'a.......................',
      'a.......................',
      'a.......................',
      'a.......................',
      'a.......................',
      'a.......................',
      'a.......................',
      'a.......................',
      'a.......................',
      'a.......................',
      '.a.......................',
      '..a.......................',
      '...a.......................',
      '....a.......................',
      '.....a.......................',
      '......a.......................',
      '.......a.......................',
      '................................',
      '................................',
      '................................',
    ],
  },
  staff: {
    palette: { a: '#8B4513', b: '#6B3410', g: '#00ff88', w: '#ffffff' },
    pixels: [
      '...............ww...............',
      '..............wggw..............',
      '.............wggggw.............',
      '............wggggggw............',
      '...........wgggggggw...........',
      '..........wgggggggggw..........',
      '.........wggggggggggw.........',
      '........wgggggggggggw........',
      '.......wggggggggggggw........',
      '......wgggggggggggggw.......',
      '.....wggggggggggggggw......',
      '....wgggggggggggggggw.....',
      '...wggggggggggggggggw....',
      '..wgggggggggggggggggw...',
      '.wggggggggggggggggggw..',
      'wgggggggggggggggggggw.',
      '.wggggggggggggggggggw..',
      '..wgggggggggggggggggw...',
      '...wggggggggggggggggw....',
      '....wgggggggggggggggw.....',
      '.....wggggggggggggggw......',
      '......wgggggggggggggw.......',
      '.......wggggggggggggw........',
      '........wgggggggggggw........',
      '.........wgggggggggw.........',
      '..........wgggggggw..........',
      '...........wgggggw...........',
      '............wgggw............',
      '.............wggw.............',
      '..............ww..............',
      '...............aa..............',
      '...............aa..............',
    ],
  },
  hp: {
    palette: { a: '#e94560', b: '#ff6b81' },
    pixels: [
      '................................',
      '................................',
      '..........aaaaaaa..............',
      '.........aaaaaaaaa.............',
      '........aaaaaaaaaaa............',
      '.......aaaaaaaaaaaaa...........',
      '......aaaaaaaaaaaaaaa..........',
      '.....aaaaaaaaaaaaaaaaa.........',
      '....aaaaaaaaaaaaaaaaaaa........',
      '...aaaaaaaaaaaaaaaaaaaaa.......',
      '..aaaaaaaaaaaaaaaaaaaaaaa......',
      '.aaaaaaaaaaaaaaaaaaaaaaaaa.....',
      '.aaaaaaaaaaaaaaaaaaaaaaaaa.....',
      '.aaaaaaaaaaaaaaaaaaaaaaaaa.....',
      '.aaaaaaaaaaaaaaaaaaaaaaaaa.....',
      '.aaaaaaaaaaaaaaaaaaaaaaaaa.....',
      '.aaaaaaaaaaaaaaaaaaaaaaaaa.....',
      '.aaaaaaaaaaaaaaaaaaaaaaaaa.....',
      '..aaaaaaaaaaaaaaaaaaaaaaa......',
      '...aaaaaaaaaaaaaaaaaaaaa.......',
      '....aaaaaaaaaaaaaaaaaaa........',
      '.....aaaaaaaaaaaaaaaaa.........',
      '......aaaaaaaaaaaaaaa..........',
      '.......aaaaaaaaaaaaa...........',
      '........aaaaaaaaaaa............',
      '.........aaaaaaaaa.............',
      '..........aaaaaaa..............',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
    ],
  },
  speed: {
    palette: { a: '#00ff88', b: '#00cc66' },
    pixels: [
      '................................',
      '..............a................',
      '.............aa................',
      '............aaa...............',
      '...........aaaa...............',
      '..........aaaaa..............',
      '.........aaaaaa..............',
      '........aaaaaaa.............',
      '.......aaaaaaaa.............',
      '......aaaaaaaaa............',
      '.....aaaaaaaaaa............',
      '....aaaaaaaaaaa...........',
      '...aaaaaaaaaaaa...........',
      '..aaaaaaaaaaaaa..........',
      '.aaaaaaaaaaaaaa..........',
      'aaaaaaaaaaaaaaa.........',
      '.aaaaaaaaaaaaaa..........',
      '..aaaaaaaaaaaaa..........',
      '...aaaaaaaaaaaa...........',
      '....aaaaaaaabba..........',
      '.....aaaaabbbba.........',
      '......aaabbbbba.........',
      '.......aabbbbba.........',
      '........abbbbba.........',
      '.........bbbba..........',
      '..........bbba..........',
      '...........bba..........',
      '............ba..........',
      '.............a..........',
      '................................',
      '................................',
      '................................',
    ],
  },
  damage: {
    palette: { a: '#ff4444', b: '#ff8800' },
    pixels: [
      '..............a..............',
      '.............aa.............',
      '............aaa............',
      '...........aaaa...........',
      '..........aaaaa..........',
      '.........aaaaaa.........',
      '........aaaaaaa........',
      '.......aaaaaaaa.......',
      '......aaaaaaaaa......',
      '.....aaaaaaaaaa.....',
      '....aaaaaaaaaaa....',
      '...aaaaaaaaaaaa...',
      '..aaaaaaaaaaaaa..',
      '.aaaaaaaaaaaaaa.',
      'aaaaaaaaaaaaaaa.',
      '.aaaaaaaaaaaaaa.',
      '..aaaaaaaaaaaaa..',
      '...aaaaaaaaaaaa...',
      '....aaaaaaaabba....',
      '.....aaaaabbbba.....',
      '......aaabbbbba......',
      '.......aabbbbba......',
      '........abbbbba......',
      '.........bbbba.......',
      '..........bbba.......',
      '...........bba.......',
      '............ba.......',
      '.............a.......',
      '......................',
      '......................',
      '......................',
      '......................',
      '......................',
    ],
  },
  crit: {
    palette: { a: '#ff0000', b: '#ffff00' },
    pixels: [
      '..............a..............',
      '.............aaa.............',
      '............aaaaa............',
      '...........aaaaaaa...........',
      '..........aaaaaaaaa..........',
      '.........aaaaaaaaaaa.........',
      '........aaaaaaaaaaaaa........',
      '.......aaaaaaaaaaaaaaa.......',
      '......aaaaaaaaaaaaaaaaa......',
      '.....aaaaaaaaaaaaaaaaaaa.....',
      '....aaaaaaaaaaaaaaaaaaaaa....',
      '...aaaaaaaaaaaaaaaaaaaaaaa...',
      '..aaaaaaaaaaaaaaaaaaaaaaaaa..',
      '.aaaaaaaaaaaaaaaaaaaaaaaaaaa.',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      '.aaaaaaaaaaaaaaaaaaaaaaaaaaa.',
      '..aaaaaaaaaaaaaaaaaaaaaaaaa..',
      '...aaaaaaaaaaaaaaaaaaaaaaa...',
      '....bbbbbbbbbbbbbbbbbbbbb....',
      '.....bbbbbbbbbbbbbbbbbbb.....',
      '......bbbbbbbbbbbbbbbbb......',
      '.......bbbbbbbbbbbbbbb.......',
      '........bbbbbbbbbbbbb........',
      '.........bbbbbbbbbbb.........',
      '..........bbbbbbbbb..........',
      '...........bbbbbbb...........',
      '............bbbbb............',
      '.............bbb.............',
      '..............b..............',
      '......................a......',
      '.....................aa......',
      '....................aaa......',
    ],
  },
  fire: {
    palette: { a: '#ff0000', b: '#ff6600', c: '#ffcc00', d: '#ffff88' },
    pixels: [
      '...............dd...............',
      '..............dddd..............',
      '.............cccccc.............',
      '............cccccccc............',
      '...........cccccccccc...........',
      '..........bbbbbbbbbbbb..........',
      '.........bbbbbbbbbbbbbb.........',
      '........bbbbbbbbbbbbbbbb........',
      '.......bbbbbbbbbbbbbbbbbb.......',
      '......bbbbbbbbbbbbbbbbbbbb......',
      '.....aaaaaaaaaaaaaaaaaaaaaa.....',
      '....aaaaaaaaaaaaaaaaaaaaaaaa....',
      '...aaaaaaaaaaaaaaaaaaaaaaaaaa...',
      '..aaaaaaaaaaaaaaaaaaaaaaaaaaaa..',
      '.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      '.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.',
      '..aaaaaaaaaaaaaaaaaaaaaaaaaaaa..',
      '...aaaaaaaaaaaaaaaaaaaaaaaaaa...',
      '....aaaaaaaaaaaaaaaaaaaaaaaa....',
      '.....aaaaaaaaaaaaaaaaaaaaaa.....',
      '......aaaaaaaaaaaaaaaaaaaa......',
      '.......aaaaaaaaaaaaaaaaaa.......',
      '........aaaaaaaaaaaaaaaa........',
      '.........aaaaaaaaaaaaaa.........',
      '..........aaaaaaaaaaaa..........',
      '...........aaaaaaaaaa...........',
      '............aaaaaaaa............',
      '.............aaaaaa.............',
      '..............aaaa..............',
      '...............aa...............',
      '................................',
      '................................',
    ],
  },
  ice: {
    palette: { a: '#88ccff', b: '#4488cc', c: '#ffffff', d: '#aaddff' },
    pixels: [
      '...............cc...............',
      '..............cccc..............',
      '.............cccccc.............',
      '............cccccccc............',
      '...........cccccccccc...........',
      '..........cccccccccccc..........',
      '.........cccccccccccccc.........',
      '........cccccccccccccccc........',
      '.......cccccccccccccccccc.......',
      '......cccccccccccccccccccc......',
      '.....cccccccccccccccccccccc.....',
      '....cccccccccccccccccccccccc....',
      '...cccccccccccccccccccccccccc...',
      '..cccccccccccccccccccccccccccc..',
      '.cccccccccccccccccccccccccccccc.',
      'cccccccccccccccccccccccccccccccc',
      '.cccccccccccccccccccccccccccccc.',
      '..cccccccccccccccccccccccccccc..',
      '...cccccccccccccccccccccccccc...',
      '....cccccccccccccccccccccccc....',
      '.....cccccccccccccccccccccc.....',
      '......cccccccccccccccccccc......',
      '.......cccccccccccccccccc.......',
      '........cccccccccccccccc........',
      '.........cccccccccccccc.........',
      '..........cccccccccccc..........',
      '...........cccccccccc...........',
      '............cccccccc............',
      '.............cccccc.............',
      '..............cccc..............',
      '...............cc...............',
      '................................',
      '................................',
    ],
  },
  thunder: {
    palette: { a: '#ffff00', b: '#ffaa00', c: '#ffffff' },
    pixels: [
      '................................',
      '..............cc................',
      '.............cccc...............',
      '............cccccc..............',
      '...........cccccccc.............',
      '..........cccccccccc............',
      '.........cccccccccccc...........',
      '........cccccccccccccc..........',
      '.......cccccccccccccccc.........',
      '......cccccccccccccccccc........',
      '.....cccccccccccccccccccc.......',
      '....cccccccccccccccccccccc......',
      '...cccccccccccccccccccccccc.....',
      '..cccccccccccccccccccccccccc....',
      '.cccccccccccccccccccccccccccc...',
      'cccccccccccccccccccccccccccccc..',
      '.cccccccccccccccccccccccccccc...',
      '..cccccccccccccccccccccccccc....',
      '...cccccccccccccccccccccccc.....',
      '....cccccccccccccccccccccc......',
      '.....cccccccccccccccccccc.......',
      '......cccccccccccccccccc........',
      '.......cccccccccccccccc.........',
      '........cccccccccccccc..........',
      '.........cccccccccccc...........',
      '..........cccccccccc............',
      '...........cccccccc.............',
      '............cccccc..............',
      '.............cccc...............',
      '..............cc................',
      '................................',
      '................................',
      '................................',
    ],
  },
  nature: {
    palette: { a: '#22aa22', b: '#44cc44', c: '#88ee88', d: '#115511' },
    pixels: [
      '...............bb...............',
      '..............bbbb..............',
      '.............bbbbbb.............',
      '............bbbbbbbb............',
      '...........bbbbbbbbbb...........',
      '..........bbbbbbbbbbbb..........',
      '.........bbbbbbbbbbbbbb.........',
      '........bbbbbbbbbbbbbbbb........',
      '.......bbbbbbbbbbbbbbbbbb.......',
      '......bbbbbbbbbbbbbbbbbbbb......',
      '.....bbbbbbbbbbbbbbbbbbbbbb.....',
      '....bbbbbbbbbbbbbbbbbbbbbbbb....',
      '...bbbbbbbbbbbbbbbbbbbbbbbbbb...',
      '..bbbbbbbbbbbbbbbbbbbbbbbbbbbb..',
      '.bbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.',
      'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
      '.bbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.',
      '..bbbbbbbbbbbbbbbbbbbbbbbbbbbb..',
      '...bbbbbbbbbbbbbbbbbbbbbbbbbb...',
      '....bbbbbbbbbbbbbbbbbbbbbbbb....',
      '.....bbbbbbbbbbbbbbbbbbbbbb.....',
      '......bbbbbbbbbbbbbbbbbbbb......',
      '.......bbbbbbbbbbbbbbbbbb.......',
      '........bbbbbbbbbbbbbbbb........',
      '.........bbbbbbbbbbbbbb.........',
      '..........bbbbbbbbbbbb..........',
      '...........bbbbbbbbbb...........',
      '............bbbbbbbb............',
      '.............bbbbbb.............',
      '..............bbbb..............',
      '...............bb...............',
      '................................',
      '................................',
    ],
  },
  coin: {
    palette: { a: '#FFD700', b: '#DAA520', c: '#FFF8DC' },
    pixels: [
      '................................',
      '..............aaaa..............',
      '............aaaaaaaa............',
      '..........aaaaaaaaaaaa..........',
      '........aaaaaaaaaaaaaaaa........',
      '......aaaaaaaaaaaaaaaaaa......',
      '.....aaaaaaaaaaaaaaaaaaaaaa.....',
      '....aaaaaaaaaaaaaaaaaaaaaaaa....',
      '...aaaaaaaaaaaaaaaaaaaaaaaaaa...',
      '..aaaaaaaaaaaaaaaaaaaaaaaaaaaa..',
      '.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.',
      '.aaaaaaaaaacccccaaaaaaaaaaaaaaa.',
      '.aaaaaaaaccccccccaaaaaaaaaaaaaa.',
      '.aaaaaaaccccccccccaaaaaaaaaaaaa.',
      '.aaaaaaaccccccccccaaaaaaaaaaaaa.',
      '.aaaaaaaccccccccccaaaaaaaaaaaaa.',
      '.aaaaaaaaccccccccaaaaaaaaaaaaaa.',
      '.aaaaaaaaaacccccaaaaaaaaaaaaaaa.',
      '.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.',
      '..aaaaaaaaaaaaaaaaaaaaaaaaaaaa..',
      '...aaaaaaaaaaaaaaaaaaaaaaaaaa...',
      '....aaaaaaaaaaaaaaaaaaaaaaaa....',
      '.....aaaaaaaaaaaaaaaaaaaaaa.....',
      '......aaaaaaaaaaaaaaaaaa......',
      '........aaaaaaaaaaaaaaaa........',
      '..........aaaaaaaaaaaa..........',
      '............aaaaaaaa............',
      '..............aaaa..............',
      '................................',
      '................................',
      '................................',
      '................................',
    ],
  },
  xp_gem: {
    palette: { a: '#00ff88', b: '#00cc66', c: '#88ffcc' },
    pixels: [
      '................................',
      '...............aa...............',
      '..............aaaa..............',
      '.............aaaaaa.............',
      '............aaaaaaaa............',
      '...........aaaaaaaaaa...........',
      '..........aaaaaaaaaaaa..........',
      '.........aaaaaaaaaaaaaa.........',
      '........aaaaaaaaaaaaaaaa........',
      '.......aaaaaaaaaaaaaaaaaa.......',
      '......aaaaaaaaaaaaaaaaaaaa......',
      '.....aaaaaaaaaaaaaaaaaaaaaa.....',
      '....aaaaaaaaaaaaaaaaaaaaaaaa....',
      '...aaaaaaaaaaaaaaaaaaaaaaaaaa...',
      '..aaaaaaaaaaaaaaaaaaaaaaaaaaaa..',
      '.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      '.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.',
      '..aaaaaaaaaaaaaaaaaaaaaaaaaaaa..',
      '...aaaaaaaaaaaaaaaaaaaaaaaaaa...',
      '....aaaaaaaaaaaaaaaaaaaaaaaa....',
      '.....aaaaaaaaaaaaaaaaaaaaaa.....',
      '......aaaaaaaaaaaaaaaaaaaa......',
      '.......aaaaaaaaaaaaaaaaaa.......',
      '........aaaaaaaaaaaaaaaa........',
      '.........aaaaaaaaaaaaaa.........',
      '..........aaaaaaaaaaaa..........',
      '...........aaaaaaaaaa...........',
      '............aaaaaaaa............',
      '.............aaaaaa.............',
      '..............aaaa..............',
      '...............aa...............',
      '................................',
    ],
  },
  skull: {
    palette: { a: '#e0e0e0', b: '#888888', c: '#333333', d: '#1a1a1a' },
    pixels: [
      '................................',
      '.............aaaaaaa............',
      '...........aaaaaaaaaaa..........',
      '.........aaaaaaaaaaaaaaa........',
      '........aaaaaaaaaaaaaaaaaa......',
      '.......aaaaaaaaaaaaaaaaaaaa.....',
      '......aaaaaaaaaaaaaaaaaaaaaa....',
      '.....aaaaaaaaaaaaaaaaaaaaaaaa...',
      '....aaaaaaaaaaaaaaaaaaaaaaaaaa..',
      '...aaaaaaaaaaaaaaaaaaaaaaaaaaaa.',
      '..aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      '.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      '.aaaaaaaaccccccccccccccaaaaaaaa.',
      '.aaaaaaaccccccccccccccccaaaaaaa.',
      '.aaaaaaaccccccccccccccccaaaaaaa.',
      '.aaaaaaaccccccccccccccccaaaaaaa.',
      '.aaaaaaaccccccccccccccccaaaaaaa.',
      '.aaaaaaaaccccccccccccccaaaaaaaa.',
      '.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      '..aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      '...aaaaaaaaaaaaaaaaaaaaaaaaaaaa.',
      '....aaaaaaaaaaaaaaaaaaaaaaaaaa..',
      '.....aaaaaaaaaaaaaaaaaaaaaaaa...',
      '......aaaaaaaabbbbbbaaaaaaaa....',
      '.......aaaaaabbbbbbbbaaaaaa.....',
      '........aaaaabbbbbbbbbaaaa......',
      '.........aaabbbbbbbbbbaaa.......',
      '..........aabbbbbbbbbbaa........',
      '...........abbbbbbbbba..........',
      '............bbbbbbbb............',
      '.............bbbbbb.............',
      '..............bbbb..............',
      '................................',
    ],
  },
  crown: {
    palette: { a: '#FFD700', b: '#DAA520', c: '#ff4444', d: '#4488ff', e: '#44cc44' },
    pixels: [
      '................................',
      '................................',
      'a.......a.......a.......a......a',
      'aa.....aaa.....aaa.....aaa....aa',
      'aab...aaab...aaab...aaab...aab.',
      'aabc..aabc..aabc..aabc..aabc..',
      'aabcc.aabcc.aabcc.aabcc.aabcc.',
      'aabccccccccccccccccccccccccbcc.',
      'aabccccccccccccccccccccccccbcc.',
      'aabccccccccccccccccccccccccbcc.',
      'aabccccccccccccccccccccccccbcc.',
      'aabccccccccccccccccccccccccbcc.',
      'aabccccccccccccccccccccccccbcc.',
      'aabccccccccccccccccccccccccbcc.',
      'aabccccccccccccccccccccccccbcc.',
      'aabccccccccccccccccccccccccbcc.',
      'aabccccccccccccccccccccccccbcc.',
      'aabccccccccccccccccccccccccbcc.',
      'aabccccccccccccccccccccccccbcc.',
      'aabccccccccccccccccccccccccbcc.',
      'aabccccccccccccccccccccccccbcc.',
      'aabccccccccccccccccccccccccbcc.',
      'aabccccccccccccccccccccccccbcc.',
      'aabccccccccccccccccccccccccbcc.',
      'aabccccccccccccccccccccccccbcc.',
      'aabccccccccccccccccccccccccbcc.',
      'aabccccccccccccccccccccccccbcc.',
      'aabccccccccccccccccccccccccbcc.',
      'aabccccccccccccccccccccccccbcc.',
      'aabccccccccccccccccccccccccbcc.',
      '................................',
      '................................',
    ],
  },
  heart: {
    palette: { a: '#e94560', b: '#ff6b81', c: '#cc2244' },
    pixels: [
      '................................',
      '................................',
      '................................',
      '................................',
      '......aa..........aa...........',
      '.....aaaa........aaaa..........',
      '....aaaaaa......aaaaaa.........',
      '...aaaaaaaa....aaaaaaaa........',
      '..aaaaaaaaaa..aaaaaaaaaa.......',
      '.aaaaaaaaaaaaaaaaaaaaaaaaaa.....',
      '.aaaaaaaaaaaaaaaaaaaaaaaaaa.....',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaa...',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaa...',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaa...',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaa...',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaa...',
      '.aaaaaaaaaaaaaaaaaaaaaaaaaa.....',
      '..aaaaaaaaaaaaaaaaaaaaaaaa......',
      '...aaaaaaaaaaaaaaaaaaaaaa.......',
      '....aaaaaaaaaaaaaaaaaaa........',
      '.....aaaaaaaaaaaaaaaaa.........',
      '......aaaaaaaaaaaaaaa..........',
      '.......aaaaaaaaaaaaa...........',
      '........aaaaaaaaaaa............',
      '.........aaaaaaaaa.............',
      '..........aaaaaaa..............',
      '...........aaaaa...............',
      '............aaa................',
      '.............a.................',
      '................................',
      '................................',
      '................................',
    ],
  },
};

const cache = new Map<string, HTMLCanvasElement>();

export function getPixelIcon(id: string, size: number = 32): HTMLCanvasElement {
  const key = `${id}_${size}`;
  const cached = cache.get(key);
  if (cached) return cached;

  const def = ICON_DEFS[id];
  if (!def) {
    const fallback = document.createElement('canvas');
    fallback.width = size;
    fallback.height = size;
    return fallback;
  }

  const canvas = document.createElement('canvas');
  canvas.width = size;
  canvas.height = size;
  const ctx = canvas.getContext('2d')!;
  ctx.imageSmoothingEnabled = false;

  const scale = size / BASE_SIZE;

  for (let y = 0; y < def.pixels.length && y < BASE_SIZE; y++) {
    const row = def.pixels[y];
    for (let x = 0; x < row.length && x < BASE_SIZE; x++) {
      const ch = row[x];
      if (ch === '.') continue;
      const color = def.palette[ch];
      if (!color) continue;
      ctx.fillStyle = color;
      ctx.fillRect(Math.floor(x * scale), Math.floor(y * scale), Math.ceil(scale), Math.ceil(scale));
    }
  }

  cache.set(key, canvas);
  return canvas;
}

export function clearIconCache(): void {
  cache.clear();
}
